apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.3
    helm:
      values: |
        crds:
          enabled: true
          keep: true
        prometheus:
          enabled: false
  syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true