apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-secret
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cluster-secret
    repoURL: https://charts.clustersecret.io/
    targetRevision: 0.4.1
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Prune=true
