apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - path: apps/longhorn
      repoURL: https://github.com/ungarscool1/infrastructure.git
      targetRevision: setup-longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system