apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - path: apps/longhorn/longhorn
      repoURL: https://github.com/ungarscool1/infrastructure.git
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
spec:
  project: default
  sources:
    - path: apps/longhorn/longhorn-config
      repoURL: https://github.com/ungarscool1/infrastructure.git
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system