apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/vaultwarden
    repoURL: https://github.com/ungarscool1/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
        automated:
          selfHeal: true
          # No prune option for vaultwarden
        syncOptions:
        - CreateNamespace=true