apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init-binding
subjects:
- kind: ServiceAccount
  name: vault-init
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vault-init-role
  apiGroup: rbac.authorization.k8s.io