apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: vault-secrets-operator-system
spec:
  address: 'http://vault.{{.Release.Namespace}}.svc.cluster.local:8200'
  skipTLSVerify: false