apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: llama-client
spec:
  type: kv-v2
  mount: applications
  path: llama/front
  destination:
    create: true
    name: llama-client
    labels:
      app.kubernetes.io/part-of: llama
    transformation:
      templates:
        PUBLIC_SSO_ACCOUNT_SETTINGS_URL:
          text: "https://{{`{{- get .Secrets \"PUBLIC_SSO_SERVER\" -}}`}}realms/{{`{{- get .Secrets \"PUBLIC_SSO_REALM\" -}}`}}/account"
  rolloutRestartTargets:
    - name: llama-client
      kind: Deployment
  refreshAfter: 1h
  vaultAuthRef: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: llama-api
spec:
  type: kv-v2
  mount: applications
  path: llama/back
  destination:
    create: true
    name: llama-api
    labels:
      app.kubernetes.io/part-of: llama
  rolloutRestartTargets:
    - name: llama-api
      kind: Deployment
  refreshAfter: 1h
  vaultAuthRef: vault-auth