ipWhitelist:
  - 10.0.0.0/8
  - 127.0.0.1/32

crowdsec:
  container_runtime: containerd
  agent:
    acquisition:
      - namespace: kube-system
        podName: traefik-*
        program: traefik
    env:
      - name: TZ
        value: "Europe/Paris"
      - name: PARSERS
        value: "crowdsecurity/cri-logs"
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
      - name: DISABLE_PARSERS
        value: "crowdsecurity/whitelists"
    persistentVolume:
      config:
        enabled: false
  lapi:
    dashboard:
      enabled: false
    env:
      - name: TZ
        value: "Europe/Paris"
      - name: ENROLL_KEY
        envFrom:
          secretKeyRef:
            name: crowdsec-auth-secret
            key: ENROLL_KEY
      - name: ENROLL_INSTANCE_NAME
        value: "k3s"
      - name: ENROLL_TAGS
        value: "k8s linux"
    persistentVolume:
      data:
        enabled: true
        storageClassName: crowdsec-data
      config:
        enabled: true
        storageClassName: crowdsec-config