apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.vaultwarden.ingress.host }}
      secretName: certificate-vaultwarden-secret
  rules:
    - host: {{ .Values.vaultwarden.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.vaultwarden.ingress.host }}
                port:
                  name: http

###apiVersion: networking.k8s.io/v1
###kind: Ingress
###metadata:
###  name: vaultwarden
###spec:
###  ingressClassName: cloudflare-tunnel
###  rules:
###    - host: {{ .Values.vaultwarden.ingress.host }}
###      http:
###        paths:
###          - backend:
###              service:
###                name: vaultwarden
###                port:
###                  number: 80
###            path: /*
###            pathType: Prefix