apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: {{ .Values.vaultwarden.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: vaultwarden
                port:
                  number: 80
            path: /*
            pathType: Prefix