apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-secret
spec:
  type: kv-v2
  mount: applications
  path: vaultwarden
  destination:
    create: true
    name: vaultwarden-secret
    labels:
      app.kubernetes.io/part-of: vaultwarden
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://vaultwarden:{{`{{- get .Secrets \"POSTGRES_PASSWORD\" -}}`}}@postgresql.{{.Release.Namespace}}.svc.cluster.local:5432/vaultwarden"
  rolloutRestartTargets:
    - name: vaultwarden
      kind: Deployment
  refreshAfter: 1h
  vaultAuthRef: vault-auth