apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: db-secret
spec:
  appName: vaultwarden
  destination:
    create: true
    name: db-secret
    transformation:
      templates:
      - name: POSTGRES_DB
        text: "{{ .POSTGRES_DB }}"
      - name: POSTGRES_USER
        text: "{{ .POSTGRES_DB }}"
      - name: POSTGRES_PASSWORD
        text: "{{ .POSTGRES_PASSWORD }}"
  refreshAfter: 1h
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vaultwarden-secret
spec:
  appName: vaultwarden
  destination:
    create: true
    name: vaultwarden-secret
    transformation:
      templates:
      - name: PUSH_INSTALLATION_ID
        text: "{{ .PUSH_INSTALLATION_ID }}"
      - name: PUSH_INSTALLATION_KEY
        text: "{{ .PUSH_INSTALLATION_KEY }}"
      - name: DOMAIN
        text: "{{ .DOMAIN }}"
      - name: DATABASE_URL
        text: "postgresql://{{ .POSTGRES_DB }}:{{ .POSTGRES_PASSWORD }}@postgresql:5432/{{ .POSTGRES_DB }}"
  refreshAfter: 1h