apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: vaultwarden-secret
spec:
  appName: vaultwarden
  destination:
    create: true
    name: vaultwarden-secret
    transformation:
      templates:
        DATABASE_URL:
          text: "postgresql://{{ .POSTGRES_DB }}:{{ .POSTGRES_PASSWORD }}@postgresql:5432/vaultwarden"
  refreshAfter: 1h