apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: kube-system
spec:
  secretName: crt-secret
  dnsNames:
  - "*.legodard.fr"
  - "legodard.fr"
  - "*.apps.legodard.fr"
  - "apps.legodard.fr"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io