apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local
    tlsStore:
      default:
        defaultCertificate:
          secretName: crt-secret
    nodeSelector:
      kubernetes.io/hostname: cloud.legodard.fr
    experimental:
      plugins:
        enabled: true
    additionalVolumes:
    - name: crowdsec-auth-secret
      secret:
        secretName: crowdsec-lapi-secrets
        optional: true
    additionalVolumeMounts:
    - name: crowdsec-auth-secret
      mountPath: /etc/crowdsec
    additionalArguments:
    - "--entrypoints.web.http.middlewares={{ .Release.Namespace }}-redirect2https@kubernetescrd"
    - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
    - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.2"