apiVersion: batch/v1
kind: Job
metadata:
  name: copy-crowdsec-secret
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: helm-traefik
      containers:
      - name: copy-secret
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            if kubectl get secret crowdsec-lapi-secrets -n waf; then
              kubectl get secret crowdsec-lapi-secrets -n waf -o yaml | \
              sed 's/namespace: waf/namespace: kube-system/' | \
              kubectl apply -f -
              break
            fi
            sleep 60
          done
      restartPolicy: Never
