apiVersion: batch/v1
kind: Job
metadata:
  name: bouncers-job
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: helm-traefik
      containers:
        - name: create-token
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl exec -it $(kubectl get pods -n {{.Release.Namespace}} -l k8s-app=waf,type=lapi -o jsonpath='{.items[0].metadata.name}') -n {{.Release.Namespace}} -- /bin/sh -c "cscli bouncers add traefik" | awk 'NR==3 {print $1}' > /tmp/csLapiSecret
              kubectl -n kube-system create secret generic crowdsec-lapi-secrets --from-file=/tmp/csLapiSecret
      initContainers:
        - name: wait-for-deployment
          image: bitnami/kubectl:latest
          command:
            - "/bin/sh"
            - "-c"
            - "until kubectl wait --for=condition=available deployment/{{.Release.Name}}-lapi -n {{.Release.Namespace}}; do sleep 1; done"
      restartPolicy: Never