longhorn:
  defaultSettings:
    allowCollectingLonghornUsageMetrics: false
    backupTarget: "CIFS"
    backupTargetCredentialSecret: "cifs-secret"
  persistence:
    defaultClass: true
    migratable: true
  preUpgradeChecker:
    jobEnabled: false
  ingress:
    enabled: true
    host: longhorn.apps.legodard.fr
    tls: true
    secureBackends: false
    tlsSecret: longhorn.local-tls
    path: /
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: true