{{- $postgresPassword := randAlphaNum 32 }}
{{- $postgresUsername := randAlphaNum 12 }}
apiVersion: v1
kind: Secret
metadata:
  name: database
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  POSTGRES_USER: {{ $postgresUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $postgresPassword | b64enc | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@postgres.default.svc.cluster.local:5432/%s" $postgresUsername $postgresPassword $postgresUsername | b64enc | quote }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: oidc
spec:
  appName: outline
  destination:
    create: true
    name: oidc
    labels:
      app.kubernetes.io/part-of: outline
    transformation:
      templates:
        OIDC_AUTH_URI:
          text: "https://{{`{{- get .Secrets \"SSO_DOMAIN\" -}}`}}/protocol/openid-connect/auth"
        OIDC_TOKEN_URI:
          text: "https://{{`{{- get .Secrets \"SSO_DOMAIN\" -}}`}}/protocol/openid-connect/token"
        OIDC_USERINFO:
          text: "https://{{`{{- get .Secrets \"SSO_DOMAIN\" -}}`}}/protocol/openid-connect/userinfo"
  refreshAfter: 1h
