apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: outline
spec:
  type: kv-v2
  mount: applications
  path: outline
  destination:
    create: true
    name: outline
    labels:
      app.kubernetes.io/part-of: outline
    transformation:
      templates:
        OIDC_AUTH_URI:
          text: "https://{{`{{- get .Secrets \"OIDC_DOMAIN\" -}}`}}/protocol/openid-connect/auth"
        OIDC_TOKEN_URI:
          text: "https://{{`{{- get .Secrets \"OIDC_DOMAIN\" -}}`}}/protocol/openid-connect/token"
        OIDC_USERINFO_URI:
          text: "https://{{`{{- get .Secrets \"OIDC_DOMAIN\" -}}`}}/protocol/openid-connect/userinfo"
        DATABASE_URL:
          text: "postgresql://{{`{{- get .Secrets \"POSTGRES_USERNAME\" -}}`}}:{{`{{- get .Secrets \"POSTGRES_PASSWORD\" -}}`}}@postgres.{{.Release.Namespace}}.svc.cluster.local:5432/{{`{{- get .Secrets \"POSTGRES_USERNAME\" -}}`}}"
  rolloutRestartTargets:
    - name: outline
      kind: Deployment
    - name: postgres
      kind: Deployment
  refreshAfter: 1h
  vaultAuthRef: vault-auth