apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: cf-secret
spec:
  appName: cloudflare-tunnel
  destination:
    create: true
    name: cf-secret
  refreshAfter: 1h