outline:
  image:
    repository: outlinewiki/outline
    tag: 0.80.2
    pullPolicy: IfNotPresent
  url: docs.legodard.fr
  storage:
    backend: s3
    volume:
      name: outline
      size: 1Gi
    s3:
      acl: private
      force_path_style: true
      bucket_name: outline
      region: eu-south-1
  configuration:
    env: production
    collaboration_url:
    web_concurrency: 1
    debug: http
    log_level: info
    default_language: en_US
    rate_limiter:
      enabled: true
      requests: 1000
      duration_window: 60
    oidc:
      scopes: openid profile email
      display_name: UAS
      username_claim: preferred_username
postgres:
  storage: 500Mi
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
redis:
  image:
    repository: redis
    tag: 7.4.0-alpine
    pullPolicy: IfNotPresent
