image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "1.23.13"

ingress:
  host: status.legodard.fr
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: waf-crowdsec-bouncer-traefik-plugin@kubernetescrd

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

volume:
  size: 4Gi
  accessMode: ReadWriteOnce
  storageClass: "longhorn"
