apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
spec:
  accessModes:
    - {{ .Values.volume.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.volume.size | default "10Gi" }}
  storageClassName: {{ .Values.volume.storageClass | default "" }}
