longhorn:
  defaultSettings:
    allowCollectingLonghornUsageMetrics: false
    backupTarget: "s3://longhorn-backup@eu-south-1/longhorn"
    backupTargetCredentialSecret: "s3-secret"
  persistence:
    defaultClass: true
    migratable: true
    defaultFsType: xfs
  preUpgradeChecker:
    jobEnabled: false
  ingress:
    enabled: true
    host: longhorn.apps.legodard.fr
    tls: false
    secureBackends: false
    path: /
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: waf-ip-whitelist@kubernetescrd,waf-redirect2https@kubernetescrd