apiVersion: v2
name: vault
description: Hashicorp Vault but with a security issue
type: application
version: 0.1.0
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.28.1