apiVersion: v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:{{ .Values.influxdb.image.tag }}
        imagePullPolicy: {{ .Values.influxdb.image.pullPolicy }}
        ports:
          - containerPort: 8086
            name: http-influx
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8086
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8086
          timeoutSeconds: 1
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
        - name: influxdb-conf
          mountPath: /etc/influxdb
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-data-pvc
      - name: influxdb-conf
        persistentVolumeClaim:
          claimName: influxdb-conf-pvc