apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: waf-ip-whitelist@kubernetescrd,waf-redirect2https@kubernetescrd
spec:
  rules:
    - host: {{ index .Values "argo-cd" "global" "domain" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http