apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-allow-local-only@kubernetescrd,default-http2https@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - {{ index .Values "argo-cd" "global" "domain" | quote }}
      secretName: certificate-argocd-secret
  rules:
    - host: {{ index .Values "argo-cd" "global" "domain" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http