apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: oidc
spec:
  appName: argocd
  destination:
    create: true
    name: oidc
    labels:
      app.kubernetes.io/part-of: argocd
  refreshAfter: 1h