argo-cd:
  global:
    domain: argocd.apps.legodard.fr
    revisionHistoryLimit: 3
    addPrometheusAnnotations: false
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
  configs:
    cm:
      create: true
      annotations: {}
      application.instanceLabelKey: argocd.argoproj.io/instance
      server.rbac.log.enforce.enable: false
      exec.enabled: false
      admin.enabled: true
      timeout.reconciliation: 180s
      timeout.hard.reconciliation: 0s
      statusbadge.enabled: false
      oidc.config: |
        name: Keycloak
        issuer: $oidc:URL
        clientID: $oidc:CLIENT_ID
        clientSecret: $oidc:CLIENT_SECRET
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
          - groups
    params:
      create: true
      annotations: {}
      otlp.address: ''
      server.insecure: true
      server.basehref: /
      server.rootpath: ''
      server.staticassets: /shared/app
      server.disable.auth: false
      server.enable.gzip: true
    rbac:
      policy.csv: |
        g, Administrators, role:admin
  dex:
    enable: false
  repoServer:
    env:
      - name: HELM_PLUGINS
        value: /gitops-tools/helm-plugins/
      - name: HELM_SECRETS_CURL_PATH
        value: /gitops-tools/curl
      - name: HELM_SECRETS_SOPS_PATH
        value: /gitops-tools/sops
      - name: HELM_SECRETS_VALS_PATH
        value: /gitops-tools/vals
      - name: HELM_SECRETS_KUBECTL_PATH
        value: /gitops-tools/kubectl
      - name: HELM_SECRETS_BACKEND
        value: sops
      # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
      - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
        value: "false"
      - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
        value: "true"
      - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
        value: "false"
      - name: HELM_SECRETS_WRAPPER_ENABLED
        value: "true"
      - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
        value: "true"
      - name: HELM_SECRETS_HELM_PATH
        value: /usr/local/bin/helm
      - name: HELM_SECRETS_LOAD_GPG_KEYS
        value: /sops-keys/key.asc
    volumes:
      - name: gitops-tools
        emptyDir: {}
      - name: sops-keys
        secret:
          secretName: sops
    volumeMounts:
      - mountPath: /gitops-tools
        name: gitops-tools
      - mountPath: /usr/local/sbin/helm
        subPath: helm
        name: gitops-tools
      - mountPath: /sops-keys/
        name: sops-keys
    initContainers:
      - name: download-tools
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: [sh, -ec]
        env:
          - name: HELM_SECRETS_VERSION
            value: "4.6.1"
          - name: KUBECTL_VERSION
            value: "1.30.2"
          - name: VALS_VERSION
            value: "0.37.3"
          - name: SOPS_VERSION
            value: "3.9.0"
        args:
          - |
            mkdir -p /gitops-tools/helm-plugins
  
            GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/')
            wget -qO /gitops-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-${GO_ARCH}
  
            GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/') && \
            wget -qO /gitops-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${GO_ARCH}/kubectl
            wget -qO /gitops-tools/sops https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.${GO_ARCH}
            wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_${GO_ARCH}.tar.gz | tar zxv -C /gitops-tools vals
            wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /gitops-tools/helm-plugins -xzf-
  
            chmod +x /gitops-tools/*
            cp /gitops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /gitops-tools/helm
        volumeMounts:
          - mountPath: /gitops-tools
            name: gitops-tools