argo-cd:
  global:
    domain: argocd.apps.legodard.fr
    revisionHistoryLimit: 3
    addPrometheusAnnotations: false
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
  configs:
    cm:
      create: true
      annotations: {}
      application.instanceLabelKey: argocd.argoproj.io/instance
      server.rbac.log.enforce.enable: false
      exec.enabled: false
      admin.enabled: true
      timeout.reconciliation: 180s
      timeout.hard.reconciliation: 0s
      statusbadge.enabled: false
      oidc.config: |
        name: Keycloak
        issuer: $oidc:URL
        clientID: $oidc:CLIENT_ID
        clientSecret: $oidc:CLIENT_SECRET
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
          - groups
    params:
      create: true
      annotations: {}
      otlp.address: ''
      server.insecure: true
      server.basehref: /
      server.rootpath: ''
      server.staticassets: /shared/app
      server.disable.auth: false
      server.enable.gzip: true
    rbac:
      policy.csv: |
        g, Administrators, role:admin
  dex:
    enable: false
